import GlobalFooter from "@/components/layouts/GlobalFooter";
import GlobalHeader from "@/components/layouts/GlobalHeader";
import GlobalModals from "@/components/layouts/GlobalModals";
import type { Metadata } from "next";
import localFont from 'next/font/local';
import "../styles/globals.scss";


const suite =  localFont({
    src: '../../public/fonts/SUITE-Variable.woff2',
    display: 'swap',
    weight: '100 900',
    variable: '--font-suite'
  })

const suit = localFont({
    src: '../../public/fonts/SUIT-Variable.woff2',
    display: 'swap',
    weight: '100 900',
    variable: '--font-suit'
  })

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body
        className={`${suit.variable} ${suite.variable} antialiased`}
      >
        <GlobalHeader />
        {children}
        <GlobalFooter />
        <GlobalModals />
      </body>
    </html>
  );
}
